### ISSUE TITLE
produce_naive gives error: "cannot produce a naive datetime from a local timestamp"

### ISSUE THREAD

**Issue by rogpeppe** [kurtraschke/pyRFC3339#9]
If I call:

    pyrfc3339.parse('2009-01-01T06:01:02-04:00', produce_naive=True)

it raises `ValueError: cannot produce a naive datetime from a local timestamp`.
It even does this when utc=True:

    pyrfc3339.parse('2009-01-01T06:01:02-04:00', utc=True, produce_naive=True)

So the only way to get a naive UTC datetime (commonly used in Python, as recommended [here](http://lucumr.pocoo.org/2011/7/15/eppur-si-muove/) for example) from an arbitrary RFC3339 time stamp with pyrfc3339 is to do:

    pyrfc3339.parse(time_str, utc=True).replace(tzinfo=None)

I'd suggest that produce_naive should imply utc=True and always produce a naive datetime in UTC.

**Comment by kurtraschke** [comment]
I started to write a long comment here about whether Armin's post, written in 2011, was still sound advice for the Python of 2024, but I think there's a better answer: pyRFC3339 is an opinionated library.  It reflects my design decision that naïve datetimes are to be avoided, and that aware datetimes should be used whenever possible, _even if_ the timezone attached to a datetime is UTC!  In this way there is never the slightest question about the timezone of a given timestamp (whether local or UTC).
